env:
  frame_stack: 4
  resize_to: (84, 84)
  state_shape: (4, 84, 84)
  render_mode: "human"
  rom_path: "roms"

agent:
  model_class: CNNModel
  kwargs:
    lr: 0.0001
    gamma: 0.99
    epsilon: 1.0
    epsilon_min: 0.1
    epsilon_decay: 0.995

training:
  num_episodes: 5000
  max_steps_per_episode: 500
  update_target_every: 100
  save_every: 500
  evaluation_episodes: 10
